version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/src/HealthcareAPI/Dockerfile
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=ddactask2.cin1pldvzrij.us-east-1.rds.amazonaws.com;Port=5432;Database=healthcaredb_dev;Username=postgres;Password=Lty123Ytl321;Include Error Detail=true
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: healthcaredb_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - healthcare_pgdata:/var/lib/postgresql/data

volumes:
  healthcare_pgdata:
